name: Build Android APK

on:
  push:
    branches: [ main ] # 或者你的主分支名称
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 或你的 Python 版本

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3 python3-pip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good openjdk-11-jdk autoconf automake libtool libffi-dev libssl-dev cython patch make
          pip install --upgrade pip
          pip install buildozer kivy pillow

      - name: Build debug APK
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-apk # 更通用的artifact名称
          # 使用通配符确保即使文件名略有变化也能上传
          path: bin/*.apk  
          # 如果apk在其他目录，请修改此路径，例如：bin/ProjectName-*-debug.apk


      - name: Debug List Files (Optional)  # 用于调试，查看bin目录下的文件
        run: ls -la bin/

